package com.itic.paris.platform.shared.config;

public enum AppConfigurationKey {
    STALE_ALERT_DAYS,
    PROMOTION_REMINDER_MONTHS,
    GDPR_OTP_RETENTION_HOURS,
    GDPR_AUDIT_LOG_RETENTION_DAYS,
    GDPR_INACTIVE_STUDENT_RETENTION_DAYS,
    INACTIVE_STUDENT_DAYS,
    JOBBOARD_SYNC_MAX_PER_PROVIDER,
    JOBBOARD_OFFER_EXPIRATION_DAYS,
    JOBBOARD_OFFER_DELETE_AFTER_DAYS,
    APPLICATION_XP_WEEKLY_LIMIT
}
